# Generated by Django 5.2.3 on 2025-06-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ekipman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100)),
                ('bulunduğu_yer', models.CharField(max_length=200)),
                ('bakım_tarihi', models.DateField()),
                ('muayene_tarihi', models.DateField()),
                ('kontrol_tarihi', models.DateField()),
            ],
        ),
    ]
