# Generated by Django 5.2.3 on 2025-06-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekipman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekipman',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to='ekipman_dosyalar/'),
        ),
    ]
