# Generated by Django 5.2.3 on 2025-06-28 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekipman', '0003_ekipman_qr_kod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gorev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('durum', models.CharField(choices=[('atanmis', 'Atanmış'), ('tamamlandi', 'Tamamlandı')], default='atanmis', max_length=20)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('ekipman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekipman.ekipman')),
                ('teknisyen', models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
