# Generated by Django 5.2.3 on 2025-06-29 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekipman', '0004_gorev'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRSorguKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adresi', models.GenericIPAddressField()),
                ('sorgulama_zamani', models.DateTimeField(auto_now_add=True)),
                ('ekipman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekipman.ekipman')),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
